# The Microsoft Store screenshot, as a recipe rather than as prose.
#
# `take-shots.ps1` beside this takes a set given the recipes for it, and
# `screenshot.ps1` under that is the driver and knows nothing about Tommy
# Flyleaf. Both are generated by ship and the same in every repository with a
# window to photograph. This file is the part that is this product's - which
# file, which shot, and what has to happen in the window before the shutter.
#
# Everything a person would change to retake the set lives at the top, and
# running it by hand on the Windows machine is the same command CI would:
#
#     powershell -ExecutionPolicy Bypass -File packaging\windows\shots.ps1
#
# The file is opened through the shell, so what appears is whatever is
# registered for `.toml` on this machine. `install.ps1 -Default` is what makes
# that this application; without it the shell opens whichever editor claimed the
# extension, and the frame is a photograph of that.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

[CmdletBinding()]
param(
    # One plain capture, and nothing else. This is how a coordinate gets
    # measured when a recipe below grows one.
    [switch] $Reference,
    [string] $OutDir
)

$ErrorActionPreference = 'Stop'

. "$PSScriptRoot\take-shots.ps1"

$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

# --- the configuration ------------------------------------------------------

# 1366x768 is the Microsoft Store's minimum for a desktop screenshot, and a
# window this size looks like a window rather than like an advertisement.
$WIDTH = 1366
$HEIGHT = 768

# The file the marketing page and the demo show, so the listing shows it too.
$FILE = Join-Path $root 'packaging\sample.toml'

# The process the window belongs to, which the driver stops first so the frame
# holds this run's window and not a previous one's.
$PROCESS = 'flyleaf'

# Where the shots land. Not committed: a screenshot is a photograph of a build,
# and it is retaken when the interface changes.
if (-not $OutDir) { $OutDir = Join-Path $root 'dist\store' }

# --- the shots --------------------------------------------------------------

function Get-Shots {
    # The window on the sample file, and no actions in it. This application
    # shows a file and does not edit it, so an interface at rest is what it
    # does rather than a frame of a viewer standing in for an editor.
    Shot '01-window' @()
}

Take-Shots -Launch @('shell', $FILE) -Process $PROCESS `
    -Width $WIDTH -Height $HEIGHT -OutDir $OutDir -Reference:$Reference
